In [1]:
import numpy as np

In [3]:
def sigmoid(x):
    s = 1 / ( 1 + np.exp(-x) )
    return s

In [ ]:
K sample including outside word

outside word a
[0, 4, 2, 3, 4, 4, 3, 1, 2, 3, 1]


outside word b 
[1, 3, 3, 3, 0, 4, 0, 2, 0, 2, 4]

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}

V
array([[-0.96735714, -0.02182641,  0.25247529],
       [ 0.73663029, -0.48088687, -0.47552459],
       [-0.27323645,  0.12538062,  0.95374082],
       [-0.56713774, -0.27178229, -0.77748902],
       [-0.59609459,  0.7795666 ,  0.19221644]])


U
array([[-0.6831809 , -0.04200519,  0.72904007],  0
       [ 0.18289107,  0.76098587, -0.62245591],  1
       [-0.61517874,  0.5147624 , -0.59713884],  2
       [-0.33867074, -0.80966534, -0.47931635],  3
       [-0.52629529, -0.78190408,  0.33412466]]) 4




c_index = 2 
o_index = 0

0.3479392611333514 + 6.126569967476927 = 6.4745092286102786

c_index = 2 
o_index = 1 

1.0043648713327047 + 7.996380489785403 = 9.000745361118108




In [23]:
6.4745092286102786 + 9.000745361118108

15.475254589728387

In [19]:
np.log(sigmoid(np.dot(np.array([ 0.18289107,  0.76098587, -0.62245591]), np.array([-0.27323645,  0.12538062,  0.95374082]))))

-1.0043648713327047

In [18]:
0.3479392611333514 + 6.126569967476927

6.4745092286102786

In [16]:
np.log(0.7061417651623674)

-0.3479392611333514

In [21]:
U = np.array([[-0.6831809 , -0.04200519,  0.72904007],
       [ 0.18289107,  0.76098587, -0.62245591],  
       [-0.61517874,  0.5147624 , -0.59713884],  
       [-0.33867074, -0.80966534, -0.47931635],  
       [-0.52629529, -0.78190408,  0.33412466]]) 
K = np.array([3, 3, 3, 0, 4, 0, 2, 0, 2, 4])

print(-U[K,:])

np.sum(np.log(sigmoid(np.matmul(-U[K,:], np.array([-0.27323645,  0.12538062,  0.95374082]).T))))

[[ 0.33867074  0.80966534  0.47931635]
 [ 0.33867074  0.80966534  0.47931635]
 [ 0.33867074  0.80966534  0.47931635]
 [ 0.6831809   0.04200519 -0.72904007]
 [ 0.52629529  0.78190408 -0.33412466]
 [ 0.6831809   0.04200519 -0.72904007]
 [ 0.61517874 -0.5147624   0.59713884]
 [ 0.6831809   0.04200519 -0.72904007]
 [ 0.61517874 -0.5147624   0.59713884]
 [ 0.52629529  0.78190408 -0.33412466]]


-7.996380489785403

In [11]:
np.dot(np.array([ 0.52629529, 0.78190408,-0.33412466]), np.array([-0.27323645,  0.12538062,  0.95374082]))

-0.36443576557101215

### b)

In [89]:
np.random.seed(0)
V = np.random.rand(2,3)
U = np.random.rand(2,3)
c_index = 1
o_index = 2
y = np.array([0,0,1]).reshape(-1,1)
h = 1e-4

In [90]:
V_cp1 = np.matrix.copy(V)
V_cp1[1, c_index] += h
V_cp2 = np.matrix.copy(V)
V_cp2[1, c_index] -= h 

In [93]:
def cond_prob(v_c, y, U):
    u_o = np.matmul(U, y)
    numerator = np.exp(np.matmul(u_o.T, v_c))
    denominator = np.sum(np.exp(np.matmul(U.T, v_c)))
    
    return (numerator / denominator).item()

def cost_func(v_c, y, U):
    return -1 * np.log(cond_prob(v_c, y, U))

def gradient(v_c, y, U):
    
    y_hat_denominator = np.sum(np.exp(np.matmul(U.T, v_c)))
    y_hat_numerator = np.exp(np.matmul(U.T, v_c))
    y_hat = (y_hat_numerator / y_hat_denominator).reshape(-1,1)

    return -1* (np.matmul(U, y) - np.matmul(U, y_hat))
    
    

In [94]:

RHS = (cost_func(V_cp1[:,c_index], y, U) - cost_func(V_cp2[:,c_index], y, U)) / (2 * h)
LHS = gradient(V[:,c_index], y, U)
print(RHS)
print(LHS)

0.06840584367562297
[[-0.15361593]
 [ 0.06840584]]


### c)  o = w 

In [127]:
def gradient(v_c, y, U):
    y_hat_denominator = np.sum(np.exp(np.matmul(U.T, v_c)))
    y_hat_numerator = np.exp(np.matmul(U.T, v_c))
    y_hat = (y_hat_numerator / y_hat_denominator).reshape(-1,1)

    return -1 * (v_c - np.dot(y_hat.squeeze(), y.squeeze()) * v_c).reshape(-1,1)
    

In [ ]:
np.random.seed(0)
V = np.random.rand(2,3)
U = np.random.rand(2,3)
c_index = 1
o_index = 2
y = np.array([0,0,1]).reshape(-1,1)
h = 1e-4

In [129]:
U_cp1 = np.matrix.copy(U)
U_cp1[1,o_index] += h
U_cp2 = np.matrix.copy(U)
U_cp2[1,o_index] -= h


In [130]:
RHS = (cost_func(V[:,c_index], y, U_cp1) - cost_func(V[:,c_index], y, U_cp2)) /  ( 2 * h)
LHS = gradient(V[:,c_index], y, U)

### c) o != w

In [136]:
def gradient(v_c, y, U):
    y_hat_denominator = np.sum(np.exp(np.matmul(U.T, v_c)))
    y_hat_numerator = np.exp(np.matmul(U.T, v_c))
    y_hat = (y_hat_numerator / y_hat_denominator).reshape(-1,1)

    return (np.dot(y_hat.squeeze(), y.squeeze()) * v_c).reshape(-1,1)
    

In [143]:
np.random.seed(0)
V = np.random.rand(2,3)
U = np.random.rand(2,3)
c_index = 1
o_index = 2
y = np.array([0,0,1]).reshape(-1,1)
h = 1e-4

In [148]:
U_cp1 = np.matrix.copy(U)
U_cp1[0,0] += h
U_cp2 = np.matrix.copy(U)
U_cp2[0,0] -= h


In [149]:
RHS = (cost_func(V[:,c_index], y, U_cp1) - cost_func(V[:,c_index], y, U_cp2)) /  ( 2 * h)
LHS = gradient(V[:,c_index], y, U)

### d)

In [152]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def gradient(x):
    return sigmoid(x) / (np.exp(x) + 1) 

In [153]:
x = 0.8 
h = 1e-4 

RHS = (sigmoid(x + h) - sigmoid(x - h)) / (2*h)
LHS = gradient(x)


In [154]:
print(RHS)
print(LHS)

0.2139096964187681
0.21390969652029443


### e)  d / d v_c

In [288]:
np.random.seed(0)
V = np.random.rand(2,5)
U = np.random.rand(2,5)
k_idx = np.array([0, 3, 4])
U_k = U[:,k_idx]
c_index = 1
o_index = 2
y = np.array([0,0,1,0,0]).reshape(-1,1)
h = 1e-4

In [271]:
U_k

array([[0.79172504, 0.92559664, 0.07103606],
       [0.0871293 , 0.77815675, 0.87001215]])

In [279]:
V_cp1 = np.matrix.copy(V)
V_cp1[1, c_index] += h
V_cp2 = np.matrix.copy(V)
V_cp2[1, c_index] -= h 

In [280]:
def cost_func(v_c, y, U_k, U):
    u_o = np.matmul(U, y)
    return (- np.log(sigmoid(np.matmul(u_o.T, v_c))) - np.sum(np.log(sigmoid(np.matmul(-U_k.T, v_c))))).item()

In [281]:
RHS = (cost_func(V_cp1[:,c_index], y, U_k, U) - cost_func(V_cp2[:,c_index], y, U_k, U)) / (2 * h)

In [282]:
RHS

0.8896341318220813

In [287]:
gradient(V[:,c_index], y, U_k, U)

array([[1.05245381],
       [0.88963413]])

In [285]:
def gradient(v_c, y, U_k, U):
    
    
    u_o = np.matmul(U, y)
    return -(1 - sigmoid( np.matmul(u_o.T, v_c))) * u_o + np.matmul(U_k,\
                                                                    (1 - sigmoid(np.matmul(-U_k.T, v_c)))).reshape(-1,1)


### e) d / d u_o

In [289]:
np.random.seed(0)
V = np.random.rand(2,5)
U = np.random.rand(2,5)
k_idx = np.array([0, 3, 4])
U_k = U[:,k_idx]
c_index = 1
o_index = 2
y = np.array([0,0,1,0,0]).reshape(-1,1)
h = 1e-4

In [304]:
U_cp1 = np.matrix.copy(U)
U_cp1[1, o_index] += h
U_cp2 = np.matrix.copy(U)
U_cp2[1, o_index] -= h 

In [305]:
RHS = (cost_func(V[:,c_index], y, U_k, U_cp1) - cost_func(V[:,c_index], y, U_k, U_cp2)) / (2 * h)

In [306]:
RHS

-0.13843011515746184

In [299]:
def gradient(v_c, y, U_k, U):
    u_o = np.matmul(U, y)
    return -1 * ( 1 - sigmoid( np.matmul(u_o.T, v_c))) * v_c

In [300]:
gradient(V[:,c_index], y, U_k, U)

array([-0.22624918, -0.13843012])

### e) d / d u_w

In [307]:
np.random.seed(0)
V = np.random.rand(2,5)
U = np.random.rand(2,5)
k_idx = np.array([0, 3, 4])
U_k = U[:,k_idx]
c_index = 1
o_index = 2
y = np.array([0,0,1,0,0]).reshape(-1,1)
h = 1e-4

In [356]:
U_k_cp1 = np.matrix.copy(U_k)
U_k_cp1[0, 0] += h
U_k_cp2 = np.matrix.copy(U_k)
U_k_cp2[0, 0] -= h

In [357]:
RHS = (cost_func(V[:,c_index], y, U_k_cp1, U) - cost_func(V[:,c_index], y, U_k_cp2, U)) / (2 * h)

In [358]:
RHS

0.46247947077526774

In [359]:
def gradient(v_c, y, U_k, U, x):

    u_x = U_k[:, x]
    return ( 1 - sigmoid( np.matmul(-u_x.T, v_c))) * v_c

In [361]:
gradient(V[:,c_index], y, U_k, U, 0)

array([0.46247947, 0.28296716])